// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjzkOghu8feqNkYLUOqvFN-_EjCEpRsdU',
    appId: '1:340706046311:web:5a3adc123dc9d2e3c73fc2',
    messagingSenderId: '340706046311',
    projectId: 'toocoob',
    authDomain: 'toocoob.firebaseapp.com',
    storageBucket: 'toocoob.firebasestorage.app',
    measurementId: 'G-6J6816WP87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPH-sEvTujoUSAUq0cgDLy11EaJmqG3kU',
    appId: '1:340706046311:android:28f62006f32f00ecc73fc2',
    messagingSenderId: '340706046311',
    projectId: 'toocoob',
    storageBucket: 'toocoob.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvPGmF-QOdyyRG91YsgkeSait1iDaYHac',
    appId: '1:340706046311:ios:331611c9b17339e3c73fc2',
    messagingSenderId: '340706046311',
    projectId: 'toocoob',
    storageBucket: 'toocoob.firebasestorage.app',
    iosBundleId: 'com.example.toocoob',
  );

}
